# Generated by Django 2.2.2 on 2019-06-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_diet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='diet_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
