# Generated by Django 2.2.2 on 2019-06-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_diet', '0003_auto_20190625_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='diet',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
