# Generated by Django 2.2.2 on 2019-06-26 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_diet', '0004_auto_20190625_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_diet.User'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cat',
            unique_together={('user', 'name')},
        ),
    ]
